<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Download Austrian Market Transparency Data – Bausteine Computergestützter Datenanalyse</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../skript/modul-glob.html" rel="next">
<link href="../skript/zeitreihen.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-41d1ed59529443dc312b46011c211845.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
<link rel="shortcut icon" href="skript/00-bilder/favicon_bcd_new.svg">
<link rel="icon" type="image/x-icon" href="logo.ico">


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../skript/marktdaten-oesterreich.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Download Austrian Market Transparency Data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../skript/00-bilder/logo_with_text_new.svg" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../skript/00-bilder/logo_with_text_new.svg" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Reading Structured Datasets Method Module</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading Structured Datasets Method Module</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/einleitung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/grundlagen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fundamentals: Characteristics of Datasets</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/datentypoperationen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Type-Dependent Operations and Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/numpy-pandas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">The NumPy and Pandas modules</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/zeitreihen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Time Series</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/marktdaten-oesterreich.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Download Austrian Market Transparency Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/modul-glob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Accessing multiple local files: <code>glob</code> module</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/maskierte-arrays.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Masked Arrays</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/dateiformate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Scientific File Formats</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/daswichtigste.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Key Takeaways (possibly as a video)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/lernzielkontrolle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Learning Assessment</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Download Austrian Market Transparency Data</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div id="758e8411" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Preparation: reload modules from the previous chapter</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>After selecting the desired period, click Export, then the Download button will appear.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="00-bilder/APG-erzeugungsdaten-2023-de.png" class="img-fluid figure-img" alt="View of the input fields to download Austrian electricity market data."></p>
<figcaption>&nbsp;</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="00-bilder/english/APG-generation-data-2023-en.png" class="img-fluid figure-img" alt="View of the input fields to download Austrian electricity market data in English."></p>
<figcaption>&nbsp;</figcaption>
</figure>
</div>
<p>The date format of the files depends on the language setting of the website (German/English).</p>
<p>:::</p>
<p>&nbsp;</p>
<p>The following file is attached to this script.</p>
<div style="font-size: 90%;">
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Data</th>
<th>Filename</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Realized Electricity Generation 2023</td>
<td>AGPT_2022-12-31T23_00_00Z_2023-12-31T23_00_00Z_15M_de_2024-06-10T09_32_38Z.csv</td>
</tr>
</tbody>
</table>
</div>
<p>In this dataset, the switch from daylight saving time to standard time on the last Sunday in October results in the 2 AM hour being recorded twice (while one hour is missing during the switch from standard to daylight saving time on the last Sunday in March). The duplicate hour is marked in the dataset as 2A and 2B. (Information from Austrian Power Grid AG, 13.08.2024)</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="00-bilder/erzeugung-aut-zeitumstellung.png" class="img-fluid figure-img" alt="Excerpt from the Austrian generation dataset. The columns 'Zeit von [CET/CEST]' and 'Zeit bis [CET/CEST]' highlight the period from 29.10.2023 02:00:00 to 29.10.2023 03:00:00 in yellow to illustrate the anomaly described above."></p>
<figcaption>Daylight saving time in the Austrian dataset</figcaption>
</figure>
</div>
<p><strong>Read the file so that columns with date and time information are recognized as datetime. Resolve the daylight saving time transition so that each day has 24 hours.</strong></p>
<div id="tip-Austria" class="callout callout-style-default callout-tip callout-titled" title="Solution for Austrian Electricity Market Data">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip&nbsp;6.1: Solution for Austrian Electricity Market Data
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Simple Approach
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The simplest solution is to generate time series and replace the columns ‘Zeit von [CET/CEST]’ and ‘Zeit bis [CET/CEST]’ with them.</p>
<pre><code>start_times = pd.date_range(start = "2023-01-01T00:00", end = "2023-12-31T23:45", freq = '15min')
end_times = pd.date_range(start = "2023-01-01T00:15", end = "2024-01-01T00:00", freq = '15min')

print(start_times[8070:8078], "\n")
print(end_times[8070:8078], "\n")</code></pre>
</div>
</div>
</div>
<p><strong>Read File and String Manipulation</strong></p>
<p>First, the file is read in. Cells that cannot be converted to datetime can be displayed using Python.</p>
<div id="fe10be77" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read file</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>generation_austria <span class="op">=</span> pd.read_csv(filepath_or_buffer <span class="op">=</span> <span class="st">"01-daten/AGPT_2022-12-31T23_00_00Z_2023-12-31T23_00_00Z_15M_de_2024-06-10T09_32_38Z.csv"</span>,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                                 sep <span class="op">=</span> <span class="st">";"</span>, decimal <span class="op">=</span> <span class="st">","</span>, thousands <span class="op">=</span> <span class="st">"."</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify cells with invalid datetime strings</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Column 'Zeit von [CET/CEST]'"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>i <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>invalid_positions <span class="op">=</span> []</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> element <span class="kw">in</span> generation_austria[<span class="st">'Zeit von [CET/CEST]'</span>]:</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>        pd.to_datetime(element, <span class="bu">format</span> <span class="op">=</span> <span class="st">"</span><span class="sc">%d</span><span class="st">.%m.%Y %H:%M:%S"</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span>:</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(element)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>        invalid_positions.append(i)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    i <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">The cells have the row indices: "</span>, invalid_positions, <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Column 'Zeit von [CET/CEST]'"</span>)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>i <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>invalid_positions <span class="op">=</span> []</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> element <span class="kw">in</span> generation_austria[<span class="st">'Zeit von [CET/CEST]'</span>]:</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>        pd.to_datetime(element, <span class="bu">format</span> <span class="op">=</span> <span class="st">"</span><span class="sc">%d</span><span class="st">.%m.%Y %H:%M:%S"</span>)</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span>:</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(element)</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>        invalid_positions.append(i)</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>    i <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">The cells have the row indices: "</span>, invalid_positions, <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Column 'Zeit von [CET/CEST]'
29.10.2023 2A:00:00
29.10.2023 2A:15:00
29.10.2023 2A:30:00
29.10.2023 2A:45:00
29.10.2023 2B:00:00
29.10.2023 2B:15:00
29.10.2023 2B:30:00
29.10.2023 2B:45:00

The cells have the row indices:  [28900, 28901, 28902, 28903, 28904, 28905, 28906, 28907] 

Column 'Zeit von [CET/CEST]'
29.10.2023 2A:00:00
29.10.2023 2A:15:00
29.10.2023 2A:30:00
29.10.2023 2A:45:00
29.10.2023 2B:00:00
29.10.2023 2B:15:00
29.10.2023 2B:30:00
29.10.2023 2B:45:00

The cells have the row indices:  [28900, 28901, 28902, 28903, 28904, 28905, 28906, 28907] 
</code></pre>
</div>
</div>
<p>To correctly read the date columns, the strings “2A” and “2B” are replaced with “02” using the <code>str.replace()</code> method. This creates a duplicate in the dataset.</p>
<div id="4ebbcf5d" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># String replace &amp; convert to datetime</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co">## Column 'Zeit von [CET/CEST]'</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>generation_austria[<span class="st">'Zeit von [CET/CEST]'</span>] <span class="op">=</span> generation_austria[<span class="st">'Zeit von [CET/CEST]'</span>].<span class="bu">str</span>.replace(pat <span class="op">=</span> <span class="st">'2A'</span>, repl <span class="op">=</span> <span class="st">'02'</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>generation_austria[<span class="st">'Zeit von [CET/CEST]'</span>] <span class="op">=</span> generation_austria[<span class="st">'Zeit von [CET/CEST]'</span>].<span class="bu">str</span>.replace(pat <span class="op">=</span> <span class="st">'2B'</span>, repl <span class="op">=</span> <span class="st">'02'</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>generation_austria[<span class="st">'Zeit von [CET/CEST]'</span>] <span class="op">=</span> pd.to_datetime(generation_austria[<span class="st">'Zeit von [CET/CEST]'</span>], <span class="bu">format</span> <span class="op">=</span> <span class="st">"</span><span class="sc">%d</span><span class="st">.%m.%Y %H:%M:%S"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co">## Column 'Zeit bis [CET/CEST]'</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>generation_austria[<span class="st">'Zeit bis [CET/CEST]'</span>] <span class="op">=</span> generation_austria[<span class="st">'Zeit bis [CET/CEST]'</span>].<span class="bu">str</span>.replace(pat <span class="op">=</span> <span class="st">'2A'</span>, repl <span class="op">=</span> <span class="st">'02'</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>generation_austria[<span class="st">'Zeit bis [CET/CEST]'</span>] <span class="op">=</span> generation_austria[<span class="st">'Zeit bis [CET/CEST]'</span>].<span class="bu">str</span>.replace(pat <span class="op">=</span> <span class="st">'2B'</span>, repl <span class="op">=</span> <span class="st">'02'</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>generation_austria[<span class="st">'Zeit bis [CET/CEST]'</span>] <span class="op">=</span> pd.to_datetime(generation_austria[<span class="st">'Zeit bis [CET/CEST]'</span>], <span class="bu">format</span> <span class="op">=</span> <span class="st">"</span><span class="sc">%d</span><span class="st">.%m.%Y %H:%M:%S"</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(generation_austria.info())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.DataFrame'&gt;
RangeIndex: 35040 entries, 0 to 35039
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype         
---  ------                        --------------  -----         
 0   Zeit von [CET/CEST]           35040 non-null  datetime64[us]
 1   Zeit bis [CET/CEST]           35040 non-null  datetime64[us]
 2   Wind [MW]                     35040 non-null  float64       
 3   Solar [MW]                    35040 non-null  float64       
 4   Biomasse [MW]                 35040 non-null  float64       
 5   Gas [MW]                      35040 non-null  float64       
 6   Kohle [MW]                    35040 non-null  float64       
 7   Öl [MW]                       35040 non-null  float64       
 8   Geothermie [MW]               35040 non-null  float64       
 9   Pumpspeicher [MW]             35040 non-null  float64       
 10  Lauf- und Schwellwasser [MW]  35040 non-null  float64       
 11  Speicher [MW]                 35040 non-null  float64       
 12  Sonstige Erneuerbare [MW]     35040 non-null  float64       
 13  Müll [MW]                     35040 non-null  float64       
 14  Andere [MW]                   35040 non-null  float64       
dtypes: datetime64[us](2), float64(13)
memory usage: 4.0 MB
None</code></pre>
</div>
</div>
<p><strong>Determine index positions of the duplicated and missing hour</strong></p>
<p>In the next step, we determine the index positions of the duplicated and the missing hour.<br>
For this purpose, a new object is created that accesses the memory area of the date columns (which is not strictly necessary).<br>
The position of the duplicated hour is determined using the method <code>pd.Series.duplicated()</code>, which returns a logical vector.<br>
This vector is then used for slicing and output of the index position.<br>
By subtracting 4, the index of the first hour is displayed (the dataset is based on quarter-hour intervals).</p>
<p><em>duplicated hour</em></p>
<div id="b0955798" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create new object</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>austria_dates <span class="op">=</span> generation_austria[[<span class="st">'Zeit von [CET/CEST]'</span>, <span class="st">'Zeit bis [CET/CEST]'</span>]].copy()</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># determine index position of the duplicated hour</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co">## Time from</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>position_duplicated_hour_from <span class="op">=</span> austria_dates[<span class="st">'Zeit von [CET/CEST]'</span>][austria_dates[<span class="st">'Zeit von [CET/CEST]'</span>].duplicated()].index <span class="op">-</span> <span class="dv">4</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The duplicated hour (Time from):</span><span class="ch">\n</span><span class="sc">{</span>austria_dates<span class="sc">.</span>loc[position_duplicated_hour_from, <span class="st">'Zeit von [CET/CEST]'</span>]<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"is located at index position</span><span class="ch">\n</span><span class="ss"> </span><span class="sc">{</span>position_duplicated_hour_from<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="ch">\n</span><span class="ss">The next hour is:</span><span class="ch">\n</span><span class="sc">{</span>austria_dates<span class="sc">.</span>loc[position_duplicated_hour_from <span class="op">+</span> <span class="dv">4</span>, <span class="st">'Zeit von [CET/CEST]'</span>]<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="ch">\n\n</span><span class="ss">Both hours are identical."</span>)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="co">### End of the shift in column Time from</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>end_shift_from <span class="op">=</span> position_duplicated_hour_from[<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The time shift in column 'Time from' ends at index position: </span><span class="sc">{</span>end_shift_from<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="co">## Time to</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>position_duplicated_hour_to <span class="op">=</span> austria_dates[<span class="st">'Zeit bis [CET/CEST]'</span>][austria_dates[<span class="st">'Zeit bis [CET/CEST]'</span>].duplicated()].index <span class="op">-</span> <span class="dv">4</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n\n</span><span class="ss">The duplicated hour (Time to):</span><span class="ch">\n</span><span class="sc">{</span>austria_dates<span class="sc">.</span>loc[position_duplicated_hour_to, <span class="st">'Zeit bis [CET/CEST]'</span>]<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"is located at index position</span><span class="ch">\n</span><span class="ss"> </span><span class="sc">{</span>position_duplicated_hour_to<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="ch">\n</span><span class="ss">The next hour is:</span><span class="ch">\n</span><span class="sc">{</span>austria_dates<span class="sc">.</span>loc[position_duplicated_hour_to <span class="op">+</span> <span class="dv">4</span>, <span class="st">'Zeit bis [CET/CEST]'</span>]<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="ch">\n\n</span><span class="ss">Both hours are identical."</span>)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="co">### End of the shift in column Time to</span></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>end_shift_to <span class="op">=</span> position_duplicated_hour_to[<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The time shift in column 'Time to' ends at index position: </span><span class="sc">{</span>end_shift_to<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>The duplicated hour (Time from):
28900   2023-10-29 02:00:00
28901   2023-10-29 02:15:00
28902   2023-10-29 02:30:00
28903   2023-10-29 02:45:00
Name: Zeit von [CET/CEST], dtype: datetime64[us]
is located at index position
 RangeIndex(start=28900, stop=28904, step=1)

The next hour is:
28904   2023-10-29 02:00:00
28905   2023-10-29 02:15:00
28906   2023-10-29 02:30:00
28907   2023-10-29 02:45:00
Name: Zeit von [CET/CEST], dtype: datetime64[us]

Both hours are identical.

The time shift in column 'Time from' ends at index position: 28903


The duplicated hour (Time to):
28899   2023-10-29 02:00:00
28900   2023-10-29 02:15:00
28901   2023-10-29 02:30:00
28902   2023-10-29 02:45:00
Name: Zeit bis [CET/CEST], dtype: datetime64[us]
is located at index position
 RangeIndex(start=28899, stop=28903, step=1)

The next hour is:
28903   2023-10-29 02:00:00
28904   2023-10-29 02:15:00
28905   2023-10-29 02:30:00
28906   2023-10-29 02:45:00
Name: Zeit bis [CET/CEST], dtype: datetime64[us]

Both hours are identical.

The time shift in column 'Time to' ends at index position: 28902</code></pre>
</div>
</div>
<p><em>missing hour</em></p>
<p>Daylight saving time begins on the last Sunday in March.<br>
The missing hour does not lie within <code>range(0, 24)</code>.<br>
This condition can be checked in four steps:</p>
<ul>
<li><p>March: <code>march = pd.Series[pd.Series.dt.month == 3]</code></p></li>
<li><p>Sundays in March: <code>sundays = march[march.dt.dayofweek == 6]</code></p></li>
<li><p>last Sunday in March: The last 23*4 entries represent the last Sunday of the month (23 because one hour is missing).<br>
<code>last_sunday = sundays[-23*4:]</code></p></li>
<li><p>missing hour: <code>np.argwhere(np.invert(pd.Series(range(0,24)).isin(last_sunday.dt.hour)))</code></p></li>
</ul>
<div id="781a6d06" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># determine index position of the missing hour</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">## Time from</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co">### Month of March</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>mask_march_from <span class="op">=</span> austria_dates[<span class="st">'Zeit von [CET/CEST]'</span>].dt.month <span class="op">==</span> <span class="dv">3</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>austria_dates_march_from <span class="op">=</span> austria_dates.loc[mask_march_from, <span class="st">'Zeit von [CET/CEST]'</span>]</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The month of March (Time from):</span><span class="ch">\n</span><span class="sc">{</span>austria_dates_march_from<span class="sc">.</span>head<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)<span class="op">;</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co">### last Sunday</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>mask_sunday_from <span class="op">=</span> (austria_dates_march_from.dt.dayofweek <span class="op">==</span> <span class="dv">6</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>last_sunday_from <span class="op">=</span> (austria_dates_march_from[mask_sunday_from])[<span class="op">-</span><span class="dv">23</span><span class="op">*</span><span class="dv">4</span>:]</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The last Sunday in March:</span><span class="ch">\n</span><span class="sc">{</span>last_sunday_from<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="co">### missing hour</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(last_sunday_from.dt.hour)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>missing_hour_from <span class="op">=</span> np.argwhere(np.invert(pd.Series(<span class="bu">range</span>(<span class="dv">0</span>,<span class="dv">24</span>)).isin(last_sunday_from.dt.hour))).item() </span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The missing hour is:</span><span class="ch">\n</span><span class="sc">{</span>missing_hour_from<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(last_sunday_from[last_sunday_from.dt.hour <span class="op">==</span> (missing_hour_from <span class="op">-</span> <span class="dv">1</span>)], </span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>      last_sunday_from[last_sunday_from.dt.hour <span class="op">==</span> (missing_hour_from <span class="op">+</span> <span class="dv">1</span>)], sep <span class="op">=</span> <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="co">### start of the shift in column Time from</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>start_shift_from <span class="op">=</span> last_sunday_from[last_sunday_from.dt.hour <span class="op">==</span> (missing_hour_from <span class="op">+</span> <span class="dv">1</span>)].index[<span class="dv">0</span>]</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The time shift in the column 'Time from' starts at index position: </span><span class="sc">{</span>start_shift_from<span class="sc">}</span><span class="ch">\n\n</span><span class="ss">"</span>)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a><span class="co">## Time to</span></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a><span class="co">### Month of March</span></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>mask_march_to <span class="op">=</span> austria_dates[<span class="st">'Zeit bis [CET/CEST]'</span>].dt.month <span class="op">==</span> <span class="dv">3</span></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>austria_dates_march_to <span class="op">=</span> austria_dates.loc[mask_march_to, <span class="st">'Zeit bis [CET/CEST]'</span>]</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The month of March (Time to):</span><span class="ch">\n</span><span class="sc">{</span>austria_dates_march_to<span class="sc">.</span>head<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)<span class="op">;</span></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a><span class="co">### last Sunday</span></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>mask_sunday_to <span class="op">=</span> (austria_dates_march_to.dt.dayofweek <span class="op">==</span> <span class="dv">6</span>)</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>last_sunday_to <span class="op">=</span> (austria_dates_march_to[mask_sunday_to])[<span class="op">-</span><span class="dv">23</span><span class="op">*</span><span class="dv">4</span>:]</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The last Sunday in March:</span><span class="ch">\n</span><span class="sc">{</span>last_sunday_to<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a><span class="co">### missing hour</span></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(last_sunday_to.dt.hour)</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>missing_hour_to <span class="op">=</span> np.argwhere(np.invert(pd.Series(<span class="bu">range</span>(<span class="dv">0</span>,<span class="dv">24</span>)).isin(last_sunday_to.dt.hour))).item() </span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The missing hour is:</span><span class="ch">\n</span><span class="sc">{</span>missing_hour_to<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(last_sunday_to[last_sunday_to.dt.hour <span class="op">==</span> (missing_hour_to <span class="op">-</span> <span class="dv">1</span>)], </span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>      last_sunday_to[last_sunday_to.dt.hour <span class="op">==</span> (missing_hour_to <span class="op">+</span> <span class="dv">1</span>)], sep <span class="op">=</span> <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a><span class="co">### start of the shift in column Time to</span></span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>start_shift_to <span class="op">=</span> last_sunday_to[last_sunday_to.dt.hour <span class="op">==</span> (missing_hour_to <span class="op">+</span> <span class="dv">1</span>)].index[<span class="dv">0</span>]</span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The time shift in the column 'Time to' starts at index position: </span><span class="sc">{</span>start_shift_to<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>The month of March (Time from):
&lt;bound method NDFrame.head of 5664   2023-03-01 00:00:00
5665   2023-03-01 00:15:00
5666   2023-03-01 00:30:00
5667   2023-03-01 00:45:00
5668   2023-03-01 01:00:00
               ...        
8631   2023-03-31 22:45:00
8632   2023-03-31 23:00:00
8633   2023-03-31 23:15:00
8634   2023-03-31 23:30:00
8635   2023-03-31 23:45:00
Name: Zeit von [CET/CEST], Length: 2972, dtype: datetime64[us]&gt;

The last Sunday in March:
8064   2023-03-26 00:00:00
8065   2023-03-26 00:15:00
8066   2023-03-26 00:30:00
8067   2023-03-26 00:45:00
8068   2023-03-26 01:00:00
               ...        
8151   2023-03-26 22:45:00
8152   2023-03-26 23:00:00
8153   2023-03-26 23:15:00
8154   2023-03-26 23:30:00
8155   2023-03-26 23:45:00
Name: Zeit von [CET/CEST], Length: 92, dtype: datetime64[us]

8064     0
8065     0
8066     0
8067     0
8068     1
        ..
8151    22
8152    23
8153    23
8154    23
8155    23
Name: Zeit von [CET/CEST], Length: 92, dtype: int32

The missing hour is:
2

8068   2023-03-26 01:00:00
8069   2023-03-26 01:15:00
8070   2023-03-26 01:30:00
8071   2023-03-26 01:45:00
Name: Zeit von [CET/CEST], dtype: datetime64[us]
8072   2023-03-26 03:00:00
8073   2023-03-26 03:15:00
8074   2023-03-26 03:30:00
8075   2023-03-26 03:45:00
Name: Zeit von [CET/CEST], dtype: datetime64[us]

The time shift in the column 'Time from' starts at index position: 8072


The month of March (Time to):
&lt;bound method NDFrame.head of 5663   2023-03-01 00:00:00
5664   2023-03-01 00:15:00
5665   2023-03-01 00:30:00
5666   2023-03-01 00:45:00
5667   2023-03-01 01:00:00
               ...        
8630   2023-03-31 22:45:00
8631   2023-03-31 23:00:00
8632   2023-03-31 23:15:00
8633   2023-03-31 23:30:00
8634   2023-03-31 23:45:00
Name: Zeit bis [CET/CEST], Length: 2972, dtype: datetime64[us]&gt;

The last Sunday in March:
8063   2023-03-26 00:00:00
8064   2023-03-26 00:15:00
8065   2023-03-26 00:30:00
8066   2023-03-26 00:45:00
8067   2023-03-26 01:00:00
               ...        
8150   2023-03-26 22:45:00
8151   2023-03-26 23:00:00
8152   2023-03-26 23:15:00
8153   2023-03-26 23:30:00
8154   2023-03-26 23:45:00
Name: Zeit bis [CET/CEST], Length: 92, dtype: datetime64[us]

8063     0
8064     0
8065     0
8066     0
8067     1
        ..
8150    22
8151    23
8152    23
8153    23
8154    23
Name: Zeit bis [CET/CEST], Length: 92, dtype: int32

The missing hour is:
2

8067   2023-03-26 01:00:00
8068   2023-03-26 01:15:00
8069   2023-03-26 01:30:00
8070   2023-03-26 01:45:00
Name: Zeit bis [CET/CEST], dtype: datetime64[us]
8071   2023-03-26 03:00:00
8072   2023-03-26 03:15:00
8073   2023-03-26 03:30:00
8074   2023-03-26 03:45:00
Name: Zeit bis [CET/CEST], dtype: datetime64[us]

The time shift in the column 'Time to' starts at index position: 8071</code></pre>
</div>
</div>
<p>With the stored index positions, the corresponding timestamps can now be shifted:</p>
<ul>
<li><p>Column <em>Time from</em>: 8072 (object <code>start_shift_from</code>) to 28903 (object <code>end_shift_from</code>)</p></li>
<li><p>Column <em>Time to</em>: 8071 (object <code>start_shift_to</code>) to 28902 (object <code>end_shift_to</code>)</p></li>
</ul>
<p>For slicing, the method <code>pd.Series.iloc[]</code> is used, which indexes exclusively — that is, the end positions must be increased by 1.<br>
By subtracting <code>pd.Timedelta(1, unit='h')</code>, the time shift is removed from the dataset.</p>
<div id="97ff7e52" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># correct time shift</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co">## Time from</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>austria_dates[<span class="st">'Zeit von [CET/CEST]'</span>].iloc[start_shift_from : end_shift_from <span class="op">+</span> <span class="dv">1</span>] <span class="op">=</span> (</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    austria_dates[<span class="st">'Zeit von [CET/CEST]'</span>]</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    .iloc[start_shift_from : end_shift_from <span class="op">+</span> <span class="dv">1</span>]</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    .subtract(pd.Timedelta(<span class="dv">1</span>, unit<span class="op">=</span><span class="st">'h'</span>))</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>generation_austria[<span class="st">'Zeit von [CET/CEST]'</span>] <span class="op">=</span> austria_dates[<span class="st">'Zeit von [CET/CEST]'</span>]</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co">## Time to</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>austria_dates[<span class="st">'Zeit bis [CET/CEST]'</span>].iloc[start_shift_to : end_shift_to <span class="op">+</span> <span class="dv">1</span>] <span class="op">=</span> (</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    austria_dates[<span class="st">'Zeit bis [CET/CEST]'</span>]</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    .iloc[start_shift_to : end_shift_to <span class="op">+</span> <span class="dv">1</span>]</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>    .subtract(pd.Timedelta(<span class="dv">1</span>, unit<span class="op">=</span><span class="st">'h'</span>))</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>generation_austria[<span class="st">'Zeit bis [CET/CEST]'</span>] <span class="op">=</span> austria_dates[<span class="st">'Zeit bis [CET/CEST]'</span>]</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a><span class="co"># verification</span></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Verification in the dataset +/- one quarter hour</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The column 'Time from'"</span>)</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(generation_austria[<span class="st">'Zeit von [CET/CEST]'</span>].iloc[start_shift_from <span class="op">-</span> <span class="dv">1</span> : end_shift_from <span class="op">+</span> <span class="dv">2</span>], <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The column 'Time to'"</span>)</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(generation_austria[<span class="st">'Zeit bis [CET/CEST]'</span>].iloc[start_shift_to <span class="op">-</span> <span class="dv">1</span> : end_shift_to <span class="op">+</span> <span class="dv">2</span>], <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Verification in the dataset +/- one quarter hour

The column 'Time from'
8071    2023-03-26 01:45:00
8072    2023-03-26 03:00:00
8073    2023-03-26 03:15:00
8074    2023-03-26 03:30:00
8075    2023-03-26 03:45:00
                ...        
28900   2023-10-29 02:00:00
28901   2023-10-29 02:15:00
28902   2023-10-29 02:30:00
28903   2023-10-29 02:45:00
28904   2023-10-29 02:00:00
Name: Zeit von [CET/CEST], Length: 20834, dtype: datetime64[us] 

The column 'Time to'
8070    2023-03-26 01:45:00
8071    2023-03-26 03:00:00
8072    2023-03-26 03:15:00
8073    2023-03-26 03:30:00
8074    2023-03-26 03:45:00
                ...        
28899   2023-10-29 02:00:00
28900   2023-10-29 02:15:00
28901   2023-10-29 02:30:00
28902   2023-10-29 02:45:00
28903   2023-10-29 02:00:00
Name: Zeit bis [CET/CEST], Length: 20834, dtype: datetime64[us] 
</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_3849/2335431116.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  austria_dates['Zeit von [CET/CEST]'].iloc[start_shift_from : end_shift_from + 1] = (
/tmp/ipykernel_3849/2335431116.py:12: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  austria_dates['Zeit bis [CET/CEST]'].iloc[start_shift_to : end_shift_to + 1] = (</code></pre>
</div>
</div>
</div>
</div>
</div>
<section id="advanced-cape-ratio-a-dataset-full-of-pitfalls" class="level4">
<h4 class="anchored" data-anchor-id="advanced-cape-ratio-a-dataset-full-of-pitfalls">Advanced: CAPE Ratio — a dataset full of pitfalls</h4>
<p>The 2013 Nobel laureate in Economic Sciences, <strong>Robert Shiller</strong>, maintains a dataset containing monthly price data of the <strong>U.S. stock index S&amp;P 500</strong> and other economic indicators for calculating the <strong>inflation-adjusted price-to-earnings ratio (CAPE Ratio)</strong>.<br>
The dataset is available on <a href="https://shillerdata.com/">Robert Shiller’s website</a> (<a href="https://img1.wsimg.com/blobby/go/e5e77e0b-59d1-44d9-ab25-4763ac982e53/downloads/ie_data.xls?ver=1712069253887">direct link to the XLS file</a>).<br>
<strong>Read in the dataset.</strong></p>
<div style="font-size: 90%;">
<table class="table">
<thead>
<tr class="header">
<th>Data</th>
<th>Filename</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Monthly price data S&amp;P500</td>
<td>shiller_data.xls</td>
</tr>
</tbody>
</table>
</div>
<div id="tip-shiller-data1" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip&nbsp;6.4: Notes and sample solution — Shiller data
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>First, open the dataset in a spreadsheet program. Some remarkable irregularities include:</p>
<ul>
<li><p>Metadata in rows 2 and 3, where some column labels are also placed, and additional metadata at the end of the file.</p></li>
<li><p>Multi-line column headers.</p></li>
<li><p>Empty columns <strong>P</strong> and <strong>N</strong>.</p></li>
<li><p>Missing values represented by <code>'NA'</code> and empty cells <code>''</code>.</p></li>
<li><p>Different formatting for the month of October in the <code>Date</code> column (<code>YYYY-M</code> format).</p></li>
</ul>
<div id="tip-shiller-data2" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip&nbsp;6.3: Hints for solving
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Due to these numerous irregularities, it’s helpful to read the <strong>data</strong> and <strong>headers</strong> separately.<br>
You can determine the correct row index either from your initial spreadsheet inspection or by reading the first 10–20 lines of the dataset in Python.<br>
This makes it easier to inspect the data and manipulate it using string-processing methods.</p>
<p>In practice, it’s often simpler to manually specify the column names using the argument<br>
<code>names = Sequence of column labels to apply</code><br>
or to define them directly in a spreadsheet editor.</p>
<p>It’s also advisable to proceed step by step, developing a separate solution for each issue, possibly using smaller dataset excerpts or generated test data.</p>
<div id="tip-shiller-data3" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip&nbsp;6.2: Complete sample solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The dataset is read using the <code>pd.read_excel()</code> function.<br>
The argument <code>sheet_name</code> is used to select the worksheet <strong>Data</strong>.<br>
With the method <code>pd.DataFrame.head(n = 10)</code>, you can identify the row index where the header ends and the data begins. In this case, the header ends at row 8, which corresponds to index <strong>7</strong> in Python.</p>
<p><strong>Read header</strong></p>
<div id="f1f52fb1" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>file_path <span class="op">=</span> <span class="st">'01-daten/shiller_data.xls'</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>shiller <span class="op">=</span> pd.read_excel(io<span class="op">=</span>file_path, sheet_name<span class="op">=</span><span class="st">'Data'</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># manually identify the end of the header and start of data (commented out)</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># print(shiller.head(n=10), "\n")</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># read header</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>shiller_head <span class="op">=</span> pd.read_excel(io<span class="op">=</span>file_path, sheet_name<span class="op">=</span><span class="st">'Data'</span>, skiprows<span class="op">=</span><span class="dv">1</span>, nrows<span class="op">=</span><span class="dv">7</span>, header<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(shiller_head, <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(shiller_head.info())  <span class="co"># empty columns are recognized as numeric</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                  0      1         2   \
0  Stock Market Data Used in "Irrational Exuberan...    NaN       NaN   
1                                 Robert J. Shiller     NaN       NaN   
2                                                NaN    NaN       NaN   
3                                                NaN    NaN       NaN   
4                                                NaN    S&amp;P       NaN   
5                                                NaN  Comp.  Dividend   
6                                               Date      P         D   

         3           4         5          6      7         8       9   ...  \
0       NaN         NaN       NaN        NaN    NaN       NaN     NaN  ...   
1       NaN         NaN       NaN        NaN    NaN       NaN     NaN  ...   
2       NaN         NaN       NaN        NaN    NaN       NaN     NaN  ...   
3       NaN    Consumer       NaN        NaN    NaN       NaN    Real  ...   
4       NaN       Price       NaN       Long    NaN       NaN   Total  ...   
5  Earnings       Index    Date     Interest   Real      Real  Return  ...   
6         E         CPI  Fraction  Rate GS10  Price  Dividend   Price  ...   

           12  13                  14  15      16       17       18  \
0  Cyclically NaN         Cyclically  NaN     NaN      NaN      NaN   
1    Adjusted NaN            Adjusted NaN     NaN      NaN      NaN   
2       Price NaN  Total Return Price NaN     NaN      NaN      NaN   
3    Earnings NaN            Earnings NaN     NaN  Monthly     Real   
4       Ratio NaN               Ratio NaN  Excess    Total    Total   
5    P/E10 or NaN         TR P/E10 or NaN    CAPE     Bond     Bond   
6        CAPE NaN             TR CAPE NaN   Yield  Returns  Returns   

                 19                 20                  21  
0               NaN                NaN                 NaN  
1               NaN                NaN                 NaN  
2               NaN                NaN                 NaN  
3               NaN                NaN                 NaN  
4           10 Year            10 Year        Real 10 Year  
5  Annualized Stock  Annualized Bonds   Excess Annualized   
6       Real Return        Real Return             Returns  

[7 rows x 22 columns] 

&lt;class 'pandas.DataFrame'&gt;
RangeIndex: 7 entries, 0 to 6
Data columns (total 22 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       3 non-null      str    
 1   1       3 non-null      str    
 2   2       2 non-null      str    
 3   3       2 non-null      str    
 4   4       4 non-null      str    
 5   5       2 non-null      str    
 6   6       3 non-null      str    
 7   7       2 non-null      str    
 8   8       2 non-null      str    
 9   9       4 non-null      str    
 10  10      2 non-null      str    
 11  11      4 non-null      str    
 12  12      7 non-null      str    
 13  13      0 non-null      float64
 14  14      7 non-null      str    
 15  15      0 non-null      float64
 16  16      3 non-null      str    
 17  17      4 non-null      str    
 18  18      4 non-null      str    
 19  19      3 non-null      str    
 20  20      3 non-null      str    
 21  21      3 non-null      str    
dtypes: float64(2), str(20)
memory usage: 1.3 KB
None</code></pre>
</div>
</div>
<p><strong>Isolating column labels</strong><br>
Next, the header can be further processed to isolate the column labels.<br>
There are several possible approaches for this task — the following method is one example, and other alternatives are shown in the next example.</p>
<p>Column-wise concatenation of strings is performed using the method <code>pd.Series.str.cat()</code>, which is only available for <code>pd.Series</code> objects.<br>
Therefore, each column is processed individually in a loop.<br>
Additionally, this method only works with the data type <code>'string'</code>, which is ensured using the method <code>astype('string')</code>.</p>
<p>Afterward, text elements that do not belong to the column labels are removed using <code>str.replace()</code>.<br>
Here, the argument <code>regex=True</code> proves useful.</p>
<div id="c662c82e" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create column labels using a loop</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>shiller_column_labels <span class="op">=</span> pd.Series()</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> column <span class="kw">in</span> shiller_head:</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    shiller_column_labels <span class="op">=</span> pd.concat([</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>        shiller_column_labels,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>        pd.Series(shiller_head[column].astype(<span class="st">'string'</span>).<span class="bu">str</span>.cat())</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="co"># clean up strings</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="co">## remove first cell content: "Stock Market Data Used in 'Irrational Exuberan...'"</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>shiller_column_labels <span class="op">=</span> shiller_column_labels.astype(<span class="st">'str'</span>).replace(shiller_head.loc[<span class="dv">0</span>, <span class="dv">0</span>], <span class="st">''</span>, regex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="co">## remove 'Robert J. Shiller'</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>shiller_column_labels <span class="op">=</span> shiller_column_labels.astype(<span class="st">'str'</span>).replace(shiller_head.loc[<span class="dv">1</span>, <span class="dv">0</span>], <span class="st">''</span>, regex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="co">## remove spaces</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="co">## regex=True to remove spaces within strings</span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>shiller_column_labels <span class="op">=</span> shiller_column_labels.astype(<span class="st">'str'</span>).replace(<span class="st">' '</span>, <span class="st">''</span>, regex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a><span class="co">## replace overly long strings</span></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>shiller_column_labels <span class="op">=</span> shiller_column_labels.astype(<span class="st">'str'</span>).replace(<span class="st">'CyclicallyAdjustedPriceEarningsRatioP/E10or'</span>, <span class="st">''</span>, regex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>shiller_column_labels <span class="op">=</span> shiller_column_labels.astype(<span class="st">'str'</span>).replace(<span class="st">'CyclicallyAdjustedTotalReturnPriceEarningsRatioTRP/E10or'</span>, <span class="st">''</span>, regex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a><span class="co">## reset index</span></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>shiller_column_labels.reset_index(inplace<span class="op">=</span><span class="va">True</span>, drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(shiller_column_labels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>0                                  Date
1                             S&amp;PComp.P
2                             DividendD
3                             EarningsE
4                 ConsumerPriceIndexCPI
5                          DateFraction
6                  LongInterestRateGS10
7                             RealPrice
8                          RealDividend
9                  RealTotalReturnPrice
10                         RealEarnings
11                 RealTRScaledEarnings
12                                 CAPE
13                                     
14                               TRCAPE
15                                     
16                      ExcessCAPEYield
17              MonthlyTotalBondReturns
18                 RealTotalBondReturns
19      10YearAnnualizedStockRealReturn
20      10YearAnnualizedBondsRealReturn
21    Real10YearExcessAnnualizedReturns
dtype: str</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Alternative approaches for string manipulation of the file header
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="using-the-numpy-data-type-str" class="level4">
<h4 class="anchored" data-anchor-id="using-the-numpy-data-type-str">Using the NumPy data type <code>'str'</code></h4>
<p>Specifying <code>dtype='str'</code> results in the use of the NumPy string data type (<code>dtype='str'</code>), which is <strong>mutable</strong>.<br>
Only with this data type does string concatenation using the method <code>pd.DataFrame.sum()</code> work properly.</p>
<div id="1993b6f2" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The NumPy string data type is mutable</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>my_array <span class="op">=</span> np.array([[<span class="st">'1'</span>, <span class="st">'2'</span>], [<span class="st">'3'</span>, <span class="st">'4'</span>]])</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>my_array[<span class="dv">0</span>] <span class="op">=</span> [<span class="st">'a'</span>, <span class="st">'b'</span>]</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>my_array</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>array([['a', 'b'],
       ['3', '4']], dtype='&lt;U1')</code></pre>
</div>
</div>
<p>With the Pandas data types <code>'string'</code> and <code>'object'</code>, the approach shown above does <strong>not</strong> work.<br>
Pandas uses the Python string type, which is <strong>immutable</strong>.<br>
This means that no method can modify an existing string in place.<br>
Instead, methods like <code>str.replace()</code> return <strong>new strings</strong>.</p>
<pre class="raw"><code>## using NumPy string data type
shiller_head = pd.read_excel(io=file_path, sheet_name='Data', skiprows=1, nrows=7, header=None)

# concatenate header with NumPy string type using pd.DataFrame.sum()
# print(shiller_head.astype('str').sum(skipna=True, axis=0))

## cleaning the dataset
### remove nan
shiller_head = shiller_head.astype('str').replace('nan', '')

### remove first cell content: "Stock Market Data Used in 'Irrational Exuberan...'"
shiller_head = shiller_head.astype('str').replace(shiller_head.loc[0, 0], '')

### remove 'Robert J. Shiller'
shiller_head = shiller_head.astype('str').replace(shiller_head.loc[1, 0], '')

### remove spaces
### regex=True to remove spaces within strings
shiller_head = shiller_head.astype('str').replace(' ', '', regex=True)

### replace overly long strings
shiller_head = shiller_head.astype('str').replace('CyclicallyAdjustedPriceEarningsRatioP/E10or', '', regex=True)
shiller_head = shiller_head.astype('str').replace('CyclicallyAdjustedTotalReturnPriceEarningsRatioTRP/E10or', '', regex=True)

### concatenate rows column-wise
shiller_head = shiller_head.astype('str').sum(skipna=True, axis=0)

print("\nConcatenated column names\n", shiller_head)</code></pre>
</section>
<section id="using-df.agg-or-df.apply" class="level4">
<h4 class="anchored" data-anchor-id="using-df.agg-or-df.apply">Using <code>DF.agg()</code> or <code>DF.apply()</code></h4>
<p>The Pandas method <code>DF.agg()</code> aggregates a DataFrame row-wise or column-wise using a specified function.<br>
The Pandas method <code>DF.apply()</code> applies a function row-wise or column-wise to a DataFrame.<br>
Essentially, both methods achieve the same result.</p>
<p>For details on using <a href="https://docs.python.org/3/reference/expressions.html#lambda">lambda expressions</a> and the <code>join</code> method from <a href="https://www.w3schools.com/python/ref_string_join.asp">Python basics</a>, refer to the provided links.</p>
<pre class="raw"><code>shiller_head = pd.read_excel(io=file_path, sheet_name='Data', skiprows=1, nrows=7, header=None)

# DF.agg()
print(shiller_head.agg(lambda x: ''.join(x.astype(str))))

# DF.apply()
print(shiller_head.apply(lambda x: ''.join(x.astype(str))))</code></pre>
</section>
</div>
</div>
</div>
<p><strong>Read in data</strong></p>
<p>When reading the data, the header is checked, and the end of the dataset is examined using the <code>.tail()</code> method to identify rows containing additional metadata.<br>
These metadata rows are then skipped using the argument <code>skipfooter=1</code>.</p>
<div id="a87c72de" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>file_path <span class="op">=</span> <span class="st">'01-daten/shiller_data.xls'</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># read data</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>shiller_data <span class="op">=</span> pd.read_excel(io<span class="op">=</span>file_path, sheet_name<span class="op">=</span><span class="st">'Data'</span>, skiprows<span class="op">=</span><span class="dv">8</span>, header<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(shiller_data.head(n<span class="op">=</span><span class="dv">2</span>), <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>shiller_data.tail(n<span class="op">=</span><span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        0     1     2    3          4            5         6           7   \
0  1871.01  4.44  0.26  0.4  12.464061  1871.041667      5.32  111.055650   
1  1871.02   4.5  0.26  0.4  12.844641  1871.125000  5.323333  109.221413   

         8           9   ...  12  13  14  15  16        17        18  \
0  6.503259  111.055650  ... NaN NaN NaN NaN NaN  1.004177  1.000000   
1  6.310571  109.747294  ... NaN NaN NaN NaN NaN  1.004180  0.974424   

         19        20        21  
0  0.130609  0.092504  0.038106  
1  0.130858  0.094635  0.036224  

[2 rows x 22 columns] 
</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">5</th>
<th data-quarto-table-cell-role="th">6</th>
<th data-quarto-table-cell-role="th">7</th>
<th data-quarto-table-cell-role="th">8</th>
<th data-quarto-table-cell-role="th">9</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">12</th>
<th data-quarto-table-cell-role="th">13</th>
<th data-quarto-table-cell-role="th">14</th>
<th data-quarto-table-cell-role="th">15</th>
<th data-quarto-table-cell-role="th">16</th>
<th data-quarto-table-cell-role="th">17</th>
<th data-quarto-table-cell-role="th">18</th>
<th data-quarto-table-cell-role="th">19</th>
<th data-quarto-table-cell-role="th">20</th>
<th data-quarto-table-cell-role="th">21</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">1836</th>
<td>2024.01</td>
<td>4815.613913</td>
<td>70.477403</td>
<td>NaN</td>
<td>308.417</td>
<td>2024.041667</td>
<td>4.06</td>
<td>4867.776285</td>
<td>71.240809</td>
<td>3.221112e+06</td>
<td>...</td>
<td>32.045123</td>
<td>NaN</td>
<td>34.620305</td>
<td>NaN</td>
<td>0.018641</td>
<td>0.991240</td>
<td>39.840706</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1837</th>
<td>2024.02</td>
<td>5011.9615</td>
<td>70.651114</td>
<td>NaN</td>
<td>310.326</td>
<td>2024.125000</td>
<td>4.21</td>
<td>5035.085170</td>
<td>70.977077</td>
<td>3.335737e+06</td>
<td>...</td>
<td>33.113433</td>
<td>NaN</td>
<td>35.790148</td>
<td>NaN</td>
<td>0.016389</td>
<td>1.003508</td>
<td>39.248767</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">1838</th>
<td>2024.03</td>
<td>5170.5725</td>
<td>70.824826</td>
<td>NaN</td>
<td>311.2805</td>
<td>2024.208333</td>
<td>4.21</td>
<td>5178.499934</td>
<td>70.933413</td>
<td>3.434666e+06</td>
<td>...</td>
<td>34.021664</td>
<td>NaN</td>
<td>36.786757</td>
<td>NaN</td>
<td>0.015239</td>
<td>1.004318</td>
<td>39.265691</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1839</th>
<td>2024.04</td>
<td>5243.77</td>
<td>NaN</td>
<td>NaN</td>
<td>311.75775</td>
<td>2024.291667</td>
<td>4.2</td>
<td>5243.770000</td>
<td>NaN</td>
<td>3.477956e+06</td>
<td>...</td>
<td>34.413463</td>
<td>NaN</td>
<td>37.183230</td>
<td>NaN</td>
<td>0.014823</td>
<td>NaN</td>
<td>39.374882</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">1840</th>
<td>NaN</td>
<td>Apr price is Apr 1st close</td>
<td>NaN</td>
<td>NaN</td>
<td>Mar/Apr CPI estimated</td>
<td>NaN</td>
<td>Apr GS10 is Mar 29th value</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>5 rows × 22 columns</p>
</div>
</div>
</div>
<p>&nbsp;</p>
<p>After removing the metadata, the detected data types are checked using the <code>.info()</code> method.</p>
<div id="1f0c5f82" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>shiller_data <span class="op">=</span> pd.read_excel(io<span class="op">=</span>file_path, sheet_name<span class="op">=</span><span class="st">'Data'</span>, skiprows<span class="op">=</span><span class="dv">8</span>, header<span class="op">=</span><span class="va">None</span>, skipfooter<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(shiller_data.head(n<span class="op">=</span><span class="dv">2</span>), <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(shiller_data.tail(n<span class="op">=</span><span class="dv">2</span>))</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># determine data types</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>shiller_data.info()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        0     1     2    3          4            5         6           7   \
0  1871.01  4.44  0.26  0.4  12.464061  1871.041667  5.320000  111.055650   
1  1871.02  4.50  0.26  0.4  12.844641  1871.125000  5.323333  109.221413   

         8           9   ...  12  13  14  15  16        17        18  \
0  6.503259  111.055650  ... NaN NaN NaN NaN NaN  1.004177  1.000000   
1  6.310571  109.747294  ... NaN NaN NaN NaN NaN  1.004180  0.974424   

         19        20        21  
0  0.130609  0.092504  0.038106  
1  0.130858  0.094635  0.036224  

[2 rows x 22 columns] 

           0          1          2   3          4            5     6   \
1838  2024.03  5170.5725  70.824826 NaN  311.28050  2024.208333  4.21   
1839  2024.04  5243.7700        NaN NaN  311.75775  2024.291667  4.20   

               7          8             9   ...         12  13         14  15  \
1838  5178.499934  70.933413  3.434666e+06  ...  34.021664 NaN  36.786757 NaN   
1839  5243.770000        NaN  3.477956e+06  ...  34.413463 NaN  37.183230 NaN   

            16        17         18  19  20  21  
1838  0.015239  1.004318  39.265691 NaN NaN NaN  
1839  0.014823       NaN  39.374882 NaN NaN NaN  

[2 rows x 22 columns]
&lt;class 'pandas.DataFrame'&gt;
RangeIndex: 1840 entries, 0 to 1839
Data columns (total 22 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       1840 non-null   float64
 1   1       1840 non-null   float64
 2   2       1839 non-null   float64
 3   3       1836 non-null   float64
 4   4       1840 non-null   float64
 5   5       1840 non-null   float64
 6   6       1840 non-null   float64
 7   7       1840 non-null   float64
 8   8       1839 non-null   float64
 9   9       1840 non-null   float64
 10  10      1836 non-null   float64
 11  11      1836 non-null   float64
 12  12      1720 non-null   float64
 13  13      0 non-null      float64
 14  14      1720 non-null   float64
 15  15      0 non-null      float64
 16  16      1720 non-null   float64
 17  17      1839 non-null   float64
 18  18      1840 non-null   float64
 19  19      1720 non-null   float64
 20  20      1720 non-null   float64
 21  21      1720 non-null   float64
dtypes: float64(22)
memory usage: 316.4 KB</code></pre>
</div>
</div>
<p><strong>Combine header and data</strong></p>
<p>Columns with index 13 (column N) and 15 (column P) are empty; these are removed from both the header and the data.<br>
All remaining columns are recognized as floating-point numbers.<br>
This means that the percentage signs in columns with indices 16 and 19–21 (Q, T:V) were handled by division by 100.<br>
With the exception of the <code>Date</code> column, all data types are now correctly recognized.</p>
<div id="5c21b7bb" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove empty columns</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>shiller_column_labels <span class="op">=</span> shiller_column_labels.drop(labels<span class="op">=</span>[<span class="dv">13</span>, <span class="dv">15</span>])</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>shiller_data <span class="op">=</span> shiller_data.drop(labels<span class="op">=</span>[<span class="dv">13</span>, <span class="dv">15</span>], axis<span class="op">=</span><span class="st">'columns'</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co"># assign column names</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>shiller_data.columns <span class="op">=</span> shiller_column_labels</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>shiller_data.info()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.DataFrame'&gt;
RangeIndex: 1840 entries, 0 to 1839
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   Date                               1840 non-null   float64
 1   S&amp;PComp.P                          1840 non-null   float64
 2   DividendD                          1839 non-null   float64
 3   EarningsE                          1836 non-null   float64
 4   ConsumerPriceIndexCPI              1840 non-null   float64
 5   DateFraction                       1840 non-null   float64
 6   LongInterestRateGS10               1840 non-null   float64
 7   RealPrice                          1840 non-null   float64
 8   RealDividend                       1839 non-null   float64
 9   RealTotalReturnPrice               1840 non-null   float64
 10  RealEarnings                       1836 non-null   float64
 11  RealTRScaledEarnings               1836 non-null   float64
 12  CAPE                               1720 non-null   float64
 13  TRCAPE                             1720 non-null   float64
 14  ExcessCAPEYield                    1720 non-null   float64
 15  MonthlyTotalBondReturns            1839 non-null   float64
 16  RealTotalBondReturns               1840 non-null   float64
 17  10YearAnnualizedStockRealReturn    1720 non-null   float64
 18  10YearAnnualizedBondsRealReturn    1720 non-null   float64
 19  Real10YearExcessAnnualizedReturns  1720 non-null   float64
dtypes: float64(20)
memory usage: 287.6 KB</code></pre>
</div>
</div>
<p><strong>Correct date format</strong></p>
<p>The next step is to correct the date format.<br>
The <code>Date</code> column contains strings in the format <code>'YYYY,MM'</code>.<br>
An exception is the month of October, which is encoded as <code>'YYYY.M'</code>.<br>
This difference is not visible in the <code>print()</code> output because the display precision is set to 2 decimal places using <code>pd.set_option("display.precision", 2)</code>.<br>
The varying string lengths can be visualized with<br>
<code>shiller_data.loc[0:12, 'Date'].astype('str').str.len()</code>.</p>
<div id="e5e6539f" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(shiller_data.loc[<span class="dv">0</span>:<span class="dv">12</span>, <span class="st">'Date'</span>], <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    pd.to_datetime(shiller_data.loc[<span class="dv">0</span>:<span class="dv">12</span>, <span class="st">'Date'</span>], <span class="bu">format</span><span class="op">=</span><span class="st">"%Y.%m"</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> <span class="pp">ValueError</span> <span class="im">as</span> error:</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(error, <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    pd.to_datetime(shiller_data.loc[<span class="dv">0</span>:<span class="dv">12</span>, <span class="st">'Date'</span>], <span class="bu">format</span><span class="op">=</span><span class="st">"%Y.%m"</span>)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(shiller_data.loc[<span class="dv">0</span>:<span class="dv">12</span>, <span class="st">'Date'</span>].astype(<span class="st">'str'</span>).<span class="bu">str</span>.<span class="bu">len</span>(), <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>0     1871.01
1     1871.02
2     1871.03
3     1871.04
4     1871.05
5     1871.06
6     1871.07
7     1871.08
8     1871.09
9     1871.10
10    1871.11
11    1871.12
12    1872.01
Name: Date, dtype: float64 

time data "1871" doesn't match format "%Y.%m". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this. 

0     7
1     7
2     7
3     7
4     7
5     7
6     7
7     7
8     7
9     6
10    7
11    7
12    7
Name: Date, dtype: int64 
</code></pre>
</div>
</div>
<p>The data type of the <code>Date</code> column is set as a string.<br>
Using a mask, strings with length 6 are identified.<br>
A <code>'0'</code> is appended to these 6-character strings to standardize the date format.<br>
Finally, the column is converted to datetime using <code>pd.to_datetime(format="%Y.%m")</code>.</p>
<div id="177aa5dd" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set data type of 'Date' column to string</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># leads to an errormessage:</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>shiller_data[<span class="st">'Date'</span>] <span class="op">=</span> shiller_data[<span class="st">'Date'</span>].astype(<span class="st">'str'</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>mask <span class="op">=</span> shiller_data[<span class="st">'Date'</span>].<span class="bu">str</span>.<span class="bu">len</span>() <span class="op">==</span> <span class="dv">6</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>shiller_data.loc[mask, <span class="st">'Date'</span>] <span class="op">=</span> shiller_data.loc[mask, <span class="st">'Date'</span>] <span class="op">+</span> <span class="st">'0'</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="co"># display string lengths</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(shiller_data.loc[<span class="dv">0</span>:<span class="dv">12</span>, <span class="st">'Date'</span>].<span class="bu">str</span>.<span class="bu">len</span>())</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(shiller_data.loc[<span class="dv">0</span>:<span class="dv">12</span>, <span class="st">'Date'</span>])</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a><span class="co"># convert 'Date' column to datetime</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>shiller_data[<span class="st">'Date'</span>] <span class="op">=</span> pd.to_datetime(shiller_data[<span class="st">'Date'</span>], <span class="bu">format</span><span class="op">=</span><span class="st">"%Y.%m"</span>)</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>shiller_data.info()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>0     7
1     7
2     7
3     7
4     7
5     7
6     7
7     7
8     7
9     7
10    7
11    7
12    7
Name: Date, dtype: int64
0     1871.01
1     1871.02
2     1871.03
3     1871.04
4     1871.05
5     1871.06
6     1871.07
7     1871.08
8     1871.09
9     1871.10
10    1871.11
11    1871.12
12    1872.01
Name: Date, dtype: str
&lt;class 'pandas.DataFrame'&gt;
RangeIndex: 1840 entries, 0 to 1839
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype         
---  ------                             --------------  -----         
 0   Date                               1840 non-null   datetime64[us]
 1   S&amp;PComp.P                          1840 non-null   float64       
 2   DividendD                          1839 non-null   float64       
 3   EarningsE                          1836 non-null   float64       
 4   ConsumerPriceIndexCPI              1840 non-null   float64       
 5   DateFraction                       1840 non-null   float64       
 6   LongInterestRateGS10               1840 non-null   float64       
 7   RealPrice                          1840 non-null   float64       
 8   RealDividend                       1839 non-null   float64       
 9   RealTotalReturnPrice               1840 non-null   float64       
 10  RealEarnings                       1836 non-null   float64       
 11  RealTRScaledEarnings               1836 non-null   float64       
 12  CAPE                               1720 non-null   float64       
 13  TRCAPE                             1720 non-null   float64       
 14  ExcessCAPEYield                    1720 non-null   float64       
 15  MonthlyTotalBondReturns            1839 non-null   float64       
 16  RealTotalBondReturns               1840 non-null   float64       
 17  10YearAnnualizedStockRealReturn    1720 non-null   float64       
 18  10YearAnnualizedBondsRealReturn    1720 non-null   float64       
 19  Real10YearExcessAnnualizedReturns  1720 non-null   float64       
dtypes: datetime64[us](1), float64(19)
memory usage: 287.6 KB</code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../skript/zeitreihen.html" class="pagination-link" aria-label="Time Series">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Time Series</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../skript/modul-glob.html" class="pagination-link" aria-label="Accessing multiple local files: `glob` module">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Accessing multiple local files: <code>glob</code> module</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>