# Learning Assessment

``` {python}
# Preparation: reload modules from the previous chapter
import numpy.ma as ma
```

## Competency Quiz


1. The following dataset is located at the file path `'01-daten/quiz-aufgabe1.csv'`.

| ID | Name | Birthdate | Salary |
|---|---|---|---|
| 1 | Anna | 1986-04-12 | 55000 |
| 2 | Bernd | 1990-05-23 | 62000 |
| 3 | Carla | 1982-11-30 | 71000 |
| 4 | David | 1975-03-15 | 58000 |

However, reading it with the Pandas function `pd.read_csv(filepath_or_buffer = filepath)` does not work as expected.

``` {python}
import pandas as pd

filepath = '01-daten/quiz-aufgabe1.csv'
task1 = pd.read_csv(filepath_or_buffer = filepath)
print(task1.info())
```

Which arguments need to be passed to the Pandas function `pd.read_csv(filepath_or_buffer = filepath)` so that the dataset is read correctly?

2. A data collection error needs to be corrected. Mark all observations for people born before 1980 as invalid.

3. Sort the `Birthdate` column in ascending order (youngest person first). Sort the entire DataFrame accordingly.

4. Why is the birthdate of the youngest person "larger" than that of the next older person?

5. A folder contains the following files: ['Datei0.jpg', 'Datei1.csv', 'Datei2.txt', 'Datei3.png']. You want to read all files with the extensions `.csv` and `.txt` using the `glob` module. How could the file path in the `pathname` argument be described to read all files `glob.glob(pathname = folderpath + '...')`?

6. Remove mask: The masked array `m_data` should be unmasked. However, the command `m_data.mask = ma.nomask` does not work. What could be the reason?

``` {python}
#| include: false
m_data = ma.MaskedArray([1, 2, 3, 4])
m_data[2] = ma.masked
m_data.harden_mask()
```

``` {python}
print(m_data, "\n")

m_data.mask = ma.nomask
print(m_data, "\n")
```

7. Which statements are correct?

    A) HDF5 and netCDF4 are specifically optimized for handling large, complex scientific datasets and support multidimensional arrays.

    B) HDF5 is a hierarchical data structure, similar in structure to a computer's directory system. NetCDF4, on the other hand, is a flat data structure and does not support directory-like data structures.

    C) Both formats, HDF5 and netCDF4, can only store one- and two-dimensional datasets.

    D) HDF5 and netCDF4 allow extensive metadata to be stored. Therefore, the formats are considered self-describing.



::: {.callout-tip collapse="true"}
## Solutions

Task 1: pd.read_csv()

``` {python}
filepath = '01-daten/quiz-aufgabe1.csv'
task1 = pd.read_csv(filepath_or_buffer = filepath, sep = ';', parse_dates = ['Geburtsdatum'], dtype = {'Name': 'string'})
print(task1.info())
```

Task 2: Mark observations as invalid

``` {python}
condition = task1['Geburtsdatum'].dt.year < 1980
print(condition, "\n")

# pd.NA for strings and integers
## NumPy data type int64 will convert the column type of Salary
task2 = task1.copy()
task2.loc[condition, :] = pd.NA
print("NumPy data type int64 converts the column type of Salary")
print(task2, "\n")
# 3  NaN   <NA>          NaT      NaN

## Pandas data type Int64 supports missing values for integers
task2 = task1.copy()
task2['Gehalt'] = task2['Gehalt'].astype('Int64')
task2['ID'] = task2['ID'].astype('Int64')
task2.loc[condition, :] = pd.NA
print("Pandas data type Int64 supports missing values for integers")
print(task2)
# 3  NaN   <NA>          NaT    <NA>
```

Task 3: Sort datetime in ascending order

``` {python}
task3 = task2.copy()
print(task3['Geburtsdatum'].sort_values(ascending = False), "\n")

# Sort the DataFrame
task3.sort_values(by = 'Geburtsdatum', ascending = False, inplace = True)
print(task3, "\n")
```

Task 4: Which date is larger and why?

Python counts time from the so-called epoch `pd.to_datetime(0)`. Younger people were born further away from the epoch.

``` {python}
task4 = pd.DataFrame({'Geburtsdatum': task3['Geburtsdatum'].sort_values(ascending = False)})
task4['timedelta_from_epoch'] = task4['Geburtsdatum'] - pd.to_datetime(0)

print(task4)
```

Task 5: glob

`glob.glob(pathname = 'folderpath' + '?????[1-2].*')` or  
`glob.glob(pathname = 'folderpath' + 'Datei[1-2].*')` or  
`glob.glob(pathname = 'folderpath' + '*[1-2].*')`

Task 6: masked Array

The masked array has a hard mask.

``` {python}
m_data.soften_mask()
m_data.mask = ma.nomask
print(m_data, "\n")
```

Task 7: HDF5 and netCDF4

Correct answers: A) and D)

::: 

## Exercises

#### A very messy dataset
The Statistical Office of the European Union, Eurostat, provides official European statistics. In the [available file at Eurostat](https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Natural_gas_price_statistics#Natural_gas_prices_for_non-household_consumers) ([direct link to XLSX file](https://ec.europa.eu/eurostat/statistics-explained/images/3/32/SE_figures_for_Gas_2023S2_v3.xlsx)) the prices for natural gas for EU member states and various EU-associated countries are recorded. Read the worksheet 'Table 1' either so that:

  - all values are read with an appropriate numeric data type.
  
  - EITHER in a two-dimensional structure where each row is an observation and each observation a row, and each column is a variable and each variable a column.  

  - OR choose a meaningful multidimensional structure.

::: {style="font-size: 90%;"}
| Data | Filename |
|---|---|
| Natural gas prices | "01-daten/SE_figures_for_Gas_2023S2_v3.xlsx" |
:::

#### A difficult format
The Federal Statistical Office publishes statistics of issued building permits, which at the time of creating this module covers the years 2015 to 2023. The data can be accessed here: <https://www-genesis.destatis.de/datenbank/online/table/31111-0006/sequenz=tabelleErgebnis&selectionname=31111-0006&zeitscheiben=1>.

Download at least two years and read the files into a single dataset. Assign each value the year of observation by adding a variable 'Year' and structure the dataset accordingly.

  - How can you extract the year from the dataset?

  - Are all variables stored in columns?

The script assumes the files are located in the following path:

::: {style="font-size: 90%;"}
| Data | Folder path |
|---|---|
| Building permits for different years | "01-daten/baugenehmigungen" |
:::
